from __future__ import annotations

INCIDENTS_SEED = [
    # ============================================================
    # LOCALES L01-L03 (Bogota, Medellin, Cali) — Colombia
    # ============================================================
    {
        "incident_id": "INC-0001",
        "title": "Carne premium llegó con fecha de vencimiento muy corta",
        "description": "El proveedor Carnes del Valle entregó 50kg de carne premium con solo 2 días de vida útil restante. No alcanza para el fin de semana.",
        "fecha_reporte": "2026-01-10",
        "local_id": "L01",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "alta",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 4,
    },
    {
        "incident_id": "INC-0002",
        "title": "Cliente insatisfecho con el punto de la carne",
        "description": "Comensal pidió término medio y recibió casi bien cocida. Reclamó en mesa y pidió hablar con el gerente.",
        "fecha_reporte": "2026-01-12",
        "local_id": "L01",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "resuelta",
        "prioridad": "media",
        "cliente_id": "C-1001",
        "cliente_email": "carlos.g@email.com",
        "cliente_telefono": "3001112233",
        "satisfaccion": 3,
    },
    {
        "incident_id": "INC-0003",
        "title": "Fallo en sistema de facturación electrónica",
        "description": "El POS dejó de emitir facturas electrónicas durante 3 horas. Se atendió con facturas manuales pero generó retrasos.",
        "fecha_reporte": "2026-01-15",
        "local_id": "L03",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 5,
    },
    {
        "incident_id": "INC-0004",
        "title": "Solicitud de reserva para 20 personas no confirmada",
        "description": "Cliente solicitó reserva corporativa para 20 personas con 2 semanas de anticipación. Nunca recibió confirmación y casi cancela.",
        "fecha_reporte": "2026-01-20",
        "local_id": "L02",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "resuelta",
        "prioridad": "alta",
        "cliente_id": "C-1002",
        "cliente_email": "maria.empresa@corp.co",
        "cliente_telefono": "3104455667",
        "satisfaccion": 2,
    },
    {
        "incident_id": "INC-0005",
        "title": "Nevera de bebidas descompuesta en Cali",
        "description": "La nevera de cervezas artesanales dejó de enfriar. Se perdió el 30% del stock y se tuvo que parar venta de cerveza 2 días.",
        "fecha_reporte": "2026-02-01",
        "local_id": "L03",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 4,
    },
    {
        "incident_id": "INC-0006",
        "title": "Demora excesiva en cocina durante San Valentín",
        "description": "El 14 de febrero los tiempos de espera superaron los 50 minutos. Varios comensales se quejaron y 3 mesas se fueron sin pedir.",
        "fecha_reporte": "2026-02-14",
        "local_id": "L01",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "resuelta",
        "prioridad": "alta",
        "cliente_id": "C-1003",
        "cliente_email": "andrea.l@email.com",
        "cliente_telefono": "3156677889",
        "satisfaccion": 2,
    },
    {
        "incident_id": "INC-0007",
        "title": "Solicitud de menú sin gluten para cliente celíaco",
        "description": "Cliente con celiaquía preguntó por opciones sin gluten. El personal no supo informar y el cliente se retiró frustrado.",
        "fecha_reporte": "2026-02-20",
        "local_id": "L02",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "abierta",
        "prioridad": "media",
        "cliente_id": "C-1004",
        "cliente_email": "laura.sin@email.co",
        "cliente_telefono": "3209988776",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0008",
        "title": "Problemas con el drenaje en cocina",
        "description": "El fregadero principal de cocina se tapó. Se llamó al servicio técnico pero tardaron 2 días en resolver. Personal de cocina trabajó con agua estancada.",
        "fecha_reporte": "2026-03-05",
        "local_id": "L01",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "alta",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 3,
    },
    # ============================================================
    # LOCALES L04-L07 (Barranquilla, Cartagena, Bucaramanga, Pereira)
    # ============================================================
    {
        "incident_id": "INC-0009",
        "title": "Cliente encontró hueso en la carne",
        "description": "Comensal reportó que su filete contenía un fragmento de hueso. Se disculparon y no cobraron el plato, pero el cliente exige revisión del proveedor.",
        "fecha_reporte": "2026-03-10",
        "local_id": "L04",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "resuelta",
        "prioridad": "critica",
        "cliente_id": "C-1005",
        "cliente_email": "pedro.bar@email.com",
        "cliente_telefono": "3012345678",
        "satisfaccion": 3,
    },
    {
        "incident_id": "INC-0010",
        "title": "Corte de luz en sede Barranquilla",
        "description": "Apagón de 4 horas en la zona. El generador de emergencia falló. Se perdió todo el inventario refrigerado (carne, queso, lácteos).",
        "fecha_reporte": "2026-03-15",
        "local_id": "L04",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 2,
    },
    {
        "incident_id": "INC-0011",
        "title": "Aire acondicionado dañado en comedor",
        "description": "Cliente reportó que el ambiente en el restaurante era insoportable por el calor. Se pidió reparación urgente del sistema de climatización.",
        "fecha_reporte": "2026-03-22",
        "local_id": "L05",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "en_progreso",
        "prioridad": "alta",
        "cliente_id": "C-1006",
        "cliente_email": "jorge.cart@email.com",
        "cliente_telefono": "3056789012",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0012",
        "title": "Error en inventario de vino tinto",
        "description": "El conteo físico de vino tinto mostró 15 botellas menos de lo que registra el sistema. Se sospecha de merma no registrada o error en recepción.",
        "fecha_reporte": "2026-04-02",
        "local_id": "L06",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "en_progreso",
        "prioridad": "media",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0013",
        "title": "Solicitud de ampliación de horario para eventos",
        "description": "Cliente interesado en celebrar su cumpleaños en la sede Pereira pero solicitó horario extendido hasta 1am. Actualmente cerramos a 11pm.",
        "fecha_reporte": "2026-04-10",
        "local_id": "L07",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "abierta",
        "prioridad": "baja",
        "cliente_id": "C-1007",
        "cliente_email": "ana.per@email.com",
        "cliente_telefono": "3114567890",
        "satisfaccion": None,
    },
    # ============================================================
    # LOCALES L08-L10 (Miami, Orlando, Tampa) — USA
    # ============================================================
    {
        "incident_id": "INC-0014",
        "title": "Customer complained about undercooked chicken",
        "description": "Client at Miami location reported chicken was undercooked. Had to be comped. Kitchen staff needs retraining on poultry temperature.",
        "fecha_reporte": "2026-04-15",
        "local_id": "L08",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "resuelta",
        "prioridad": "alta",
        "cliente_id": "C-1008",
        "cliente_email": "john.doe@email.com",
        "cliente_telefono": "3051112233",
        "satisfaccion": 3,
    },
    {
        "incident_id": "INC-0015",
        "title": "Roach sighting in dining area",
        "description": "A customer reported seeing a cockroach near their table. Immediate fumigation required. Health inspection risk.",
        "fecha_reporte": "2026-04-22",
        "local_id": "L08",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "resuelta",
        "prioridad": "critica",
        "cliente_id": "C-1009",
        "cliente_email": "sarah.m@email.com",
        "cliente_telefono": "3059988776",
        "satisfaccion": 1,
    },
    {
        "incident_id": "INC-0016",
        "title": "POS system not accepting credit cards",
        "description": "Credit card terminal went down for 2 hours. Lost around $2,800 in potential card sales. Customers had to pay in cash or leave.",
        "fecha_reporte": "2026-05-03",
        "local_id": "L09",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "en_progreso",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0017",
        "title": "Shortage of takeout packaging",
        "description": "Orlando location ran out of takeout boxes and bags. Had to use alternatives not branded. Affects customer experience.",
        "fecha_reporte": "2026-05-10",
        "local_id": "L09",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "media",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 4,
    },
    {
        "incident_id": "INC-0018",
        "title": "Water damage in storage area",
        "description": "A pipe burst in Tampa's storage room. Destroyed cardboard packaging and some dry goods. Insurance claim filed.",
        "fecha_reporte": "2026-05-20",
        "local_id": "L10",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "abierta",
        "prioridad": "alta",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    # ============================================================
    # LOCALES L11-L14 (Bogota, Medellin, Cali, Miami — segundas)
    # ============================================================
    {
        "incident_id": "INC-0019",
        "title": "Capacitación insuficiente a nuevo personal de cocina",
        "description": "Tres nuevos cocineros en sede Bogotá 2 no recibieron inducción completa. Errores en porciones y tiempos de cocción.",
        "fecha_reporte": "2026-06-01",
        "local_id": "L11",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "en_progreso",
        "prioridad": "alta",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0020",
        "title": "Cliente dejó reseña negativa por servicio lento",
        "description": "En Google Maps, cliente reportó que esperó 40 minutos por su plato principal. La reseña afectó la calificación del local.",
        "fecha_reporte": "2026-06-05",
        "local_id": "L12",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "abierta",
        "prioridad": "alta",
        "cliente_id": "C-1010",
        "cliente_email": "diego.r@email.com",
        "cliente_telefono": "3171234567",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0021",
        "title": "Solicitud de opciones vegetarianas en el menú",
        "description": "Grupo de clientes frecuentes solicita que se incluyan opciones sin carne en el menú. Han dejado de venir por falta de variedad.",
        "fecha_reporte": "2026-06-15",
        "local_id": "L13",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "abierta",
        "prioridad": "media",
        "cliente_id": "C-1011",
        "cliente_email": "veggie.group@email.com",
        "cliente_telefono": "3123456789",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0022",
        "title": "Problemas con la báscula de porciones",
        "description": "La báscula digital de cocina está descalibrada. Las porciones de carne varían hasta 150g entre platos. Afecta control de costos.",
        "fecha_reporte": "2026-06-20",
        "local_id": "L14",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "resuelta",
        "prioridad": "media",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": 4,
    },
    {
        "incident_id": "INC-0023",
        "title": "Cliente alérgico al maní no fue informado",
        "description": "Comensal preguntó si algún plato contenía maní. El mesero no lo sabía y ningún plato tenía la información. Por suerte el cliente llevaba su medicación.",
        "fecha_reporte": "2026-07-01",
        "local_id": "L11",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "en_progreso",
        "prioridad": "critica",
        "cliente_id": "C-1012",
        "cliente_email": "luisa.alerg@email.com",
        "cliente_telefono": "3187654321",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0024",
        "title": "Robo menor en caja durante cambio de turno",
        "description": "Durante el cambio de turno en Miami (L14), faltaron $340 en caja. Se revisaron cámaras y un empleado temporal fue identificado.",
        "fecha_reporte": "2026-07-10",
        "local_id": "L14",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "abierta",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0025",
        "title": "Cliente solicita programa de fidelización",
        "description": "Un cliente frecuente (visita 3 veces por semana) pregunta si hay tarjeta de puntos o descuentos por lealtad. No tenemos programa activo.",
        "fecha_reporte": "2026-07-15",
        "local_id": "L02",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "abierta",
        "prioridad": "baja",
        "cliente_id": "C-1013",
        "cliente_email": "fidel.cliente@email.com",
        "cliente_telefono": "3145678901",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0026",
        "title": "Cockroach sighting at Miami 2nd location",
        "description": "Multiple customers reported seeing cockroaches near the bar area. Health inspector visit scheduled. Urgent pest control needed.",
        "fecha_reporte": "2026-07-22",
        "local_id": "L14",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "abierta",
        "prioridad": "critica",
        "cliente_id": "C-1014",
        "cliente_email": "david@email.com",
        "cliente_telefono": "7861112233",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0027",
        "title": "Problemas de conectividad con plataforma de domicilios",
        "description": "La tablet de domicilios (Rappi) no recibe pedidos desde hace 3 días. El servicio técnico no ha resuelto. Se pierden ~$400/día en pedidos.",
        "fecha_reporte": "2026-07-28",
        "local_id": "L05",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "en_progreso",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0028",
        "title": "Solicitud de menú infantil",
        "description": "Varios clientes con niños han preguntado por opciones de menú infantil. Actualmente solo tenemos platos completos sin opciones para niños.",
        "fecha_reporte": "2026-08-01",
        "local_id": "L08",
        "origen": "cliente",
        "categoria": "solicitud",
        "estado": "abierta",
        "prioridad": "media",
        "cliente_id": "C-1015",
        "cliente_email": "parents.miami@email.com",
        "cliente_telefono": "3054455667",
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0029",
        "title": "Avería en el horno de brasas principal",
        "description": "El horno principal de Brasaland Sede 1 (Bogotá) dejó de funcionar. Solo queda el horno secundario. Capacidad de producción reducida al 50%.",
        "fecha_reporte": "2026-08-05",
        "local_id": "L01",
        "origen": "interno",
        "categoria": "fallo_operativo",
        "estado": "abierta",
        "prioridad": "critica",
        "cliente_id": None,
        "cliente_email": None,
        "cliente_telefono": None,
        "satisfaccion": None,
    },
    {
        "incident_id": "INC-0030",
        "title": "Cliente reporta intoxicación leve",
        "description": "Cliente que comió en la sede de Medellín 2 reportó malestar estomacal horas después. Se investiga si fue la carne o la salsa. Se tomó muestra del lote.",
        "fecha_reporte": "2026-08-10",
        "local_id": "L12",
        "origen": "cliente",
        "categoria": "queja",
        "estado": "abierta",
        "prioridad": "critica",
        "cliente_id": "C-1016",
        "cliente_email": "salud@email.com",
        "cliente_telefono": "3101112233",
        "satisfaccion": None,
    },
]